% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Sep-2020 17:06:33
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

X = saveVarsMat.X; % <102x100x3 uint8> too many elements

clear saveVarsMat;
